from __future__ import annotations

import pygame


SPECTRUM_PYGAME_KEYMAP = {
    pygame.K_LSHIFT: (0, 0),
    pygame.K_z: (0, 1),
    pygame.K_x: (0, 2),
    pygame.K_c: (0, 3),
    pygame.K_v: (0, 4),
    pygame.K_a: (1, 0),
    pygame.K_s: (1, 1),
    pygame.K_d: (1, 2),
    pygame.K_f: (1, 3),
    pygame.K_g: (1, 4),
    pygame.K_q: (2, 0),
    pygame.K_w: (2, 1),
    pygame.K_e: (2, 2),
    pygame.K_r: (2, 3),
    pygame.K_t: (2, 4),
    pygame.K_1: (3, 0),
    pygame.K_2: (3, 1),
    pygame.K_3: (3, 2),
    pygame.K_4: (3, 3),
    pygame.K_5: (3, 4),
    pygame.K_0: (4, 0),
    pygame.K_9: (4, 1),
    pygame.K_8: (4, 2),
    pygame.K_7: (4, 3),
    pygame.K_6: (4, 4),
    pygame.K_p: (5, 0),
    pygame.K_o: (5, 1),
    pygame.K_i: (5, 2),
    pygame.K_u: (5, 3),
    pygame.K_y: (5, 4),
    pygame.K_RETURN: (6, 0),
    pygame.K_l: (6, 1),
    pygame.K_k: (6, 2),
    pygame.K_j: (6, 3),
    pygame.K_h: (6, 4),
    pygame.K_SPACE: (7, 0),
    pygame.K_RCTRL: (7, 1),
    pygame.K_m: (7, 2),
    pygame.K_n: (7, 3),
    pygame.K_b: (7, 4),
}
